sudo: required
language: generic
services:
  - docker

before_install:
  - docker build -t antoniok/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true antoniok/docker-react yarn test -- --coverage