version: 2.1
jobs:
  build:
    docker:
      - image: cimg/node:16.10.0
    steps:
      - checkout
      - setup_remote_docker:
          version: 19.03.13
          docker_layer_caching: true
      - run:
          name: build image
          command: docker build -t antoniok/docker-react -f Dockerfile.dev .
      - run:
          name: script
          command: docker run antoniok/docker-react yarn test -- --coverage