version: 2.1
jobs:
  build:
    docker:
      - image: cimg/node:16.10.0
    steps:
      - checkout
      - run:
          name: Pre-build image
          command: docker build -t antoniok/docker-react -f Dockerfile.dev .
      - run:
          name: script
          command: docker run -it antoniok/docker-react yarn test -- --coverage