name: frontend

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: build docker image
        run: docker build -t antoniok/frontend -f Dockerfile.dev .
      - name: test the app
        run: docker run antoniok/frontend yarn test -- --coverage